### ISSUE TITLE
rnd.any does not work for multisets

### ISSUE THREAD

**Issue by tqa3001** [MikeMirzayanov/testlib#171]
error: no match for 'operator+'

**Comment by HeRaNO** [comment]
seems should use `std::advance` or `std::next` instead of `+` in

https://github.com/MikeMirzayanov/testlib/blob/7fd543d7e6ae36a04bb382c5ebb4eee254362c6a/testlib.h#L889

and

https://github.com/MikeMirzayanov/testlib/blob/7fd543d7e6ae36a04bb382c5ebb4eee254362c6a/testlib.h#L898

BTW, in function `wany` has the same issue.

**Comment by MikeMirzayanov** [comment]
Fixed
